apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: authkit-demo
spec:
  # Mudamos para LoadBalancer para aceitar tr√°fego na porta 443 real
  type: LoadBalancer
  selector:
    app: caddy
  ports:
  - name: https
    port: 443
    targetPort: 443